import test from "node:test";import assert from "node:assert/strict";
import {RightsLineage,assertAdmControl,assertDpiaGate,assertNonAdvisedJourney,assertProcessingControlApproved,assertRealDataActivation,lifecycleDecision} from "../src/sp5-data-governance.ts";

const approvedFlow={flowKey:"QUOTE",purpose:"obtain and compare customer-directed motor quotations",lawfulBasis:"CONTRACT" as const,dataRole:"CONTROLLER" as const,approved:true,approvalReference:"GOV-001"};
test("S5-G9 real-data activation fails closed",()=>{assert.throws(()=>assertRealDataActivation({realDataRequested:true,productionAuthorised:false,processingControls:[approvedFlow]}),/PRODUCTION_AUTHORISATION/);assert.throws(()=>assertRealDataActivation({realDataRequested:true,productionAuthorised:true,processingControls:[]}),/PROCESSING_CONTROLS/);assert.doesNotThrow(()=>assertRealDataActivation({realDataRequested:true,productionAuthorised:true,processingControls:[approvedFlow]}));});
test("S5-G10 purpose lawful-basis and data-role metadata must be approved",()=>{assert.doesNotThrow(()=>assertProcessingControlApproved(approvedFlow));assert.throws(()=>assertProcessingControlApproved({...approvedFlow,dataRole:"TBD"}),/CLASSIFICATION_TBD/);assert.throws(()=>assertProcessingControlApproved({...approvedFlow,approved:false,approvalReference:undefined}),/APPROVAL_REQUIRED/);});
test("S5-G11 retention deletion and legal hold are deterministic and approval gated",()=>{const rule={recordClass:"CUSTOMER_QUOTE",retainDays:30,approved:true,approvalReference:"RET-001"};assert.equal(lifecycleDecision({id:"1",recordClass:"CUSTOMER_QUOTE",createdDay:0,legalHold:false,deleted:false},rule,31),"DELETE");assert.equal(lifecycleDecision({id:"1",recordClass:"CUSTOMER_QUOTE",createdDay:0,legalHold:true,deleted:false},rule,31),"RETAIN_LEGAL_HOLD");assert.throws(()=>lifecycleDecision({id:"1",recordClass:"CUSTOMER_QUOTE",createdDay:0,legalHold:false,deleted:false},{...rule,approved:false},31),/SCHEDULE_APPROVAL/);});
test("S5-G12 correction and restriction preserve historical lineage",()=>{const l=new RightsLineage({postcode:"A",occupation:"X"});l.correct({postcode:"B"});l.restrict();const history=l.access();assert.equal(history.length,3);assert.equal(history[0]!.facts.postcode,"A");assert.equal(history[1]!.facts.postcode,"B");assert.equal(history[1]!.supersedes,1);assert.equal(history[2]!.restricted,true);});
test("S5-G13 DPIA gate fails closed when required but unapproved",()=>{assert.doesNotThrow(()=>assertDpiaGate({required:false,approved:false}));assert.throws(()=>assertDpiaGate({required:true,approved:false}),/DPIA_APPROVAL_REQUIRED/);assert.doesNotThrow(()=>assertDpiaGate({required:true,approved:true,approvalReference:"DPIA-001"}));});
test("S5-G14 ADM classification requires recorded classification and challenge where significant",()=>{assert.throws(()=>assertAdmControl({classification:"TBD",humanChallengeAvailable:false}),/CLASSIFICATION_REQUIRED/);assert.throws(()=>assertAdmControl({classification:"SIGNIFICANT_AUTOMATED_DECISION",humanChallengeAvailable:false,classificationReference:"ADM-001"}),/HUMAN_CHALLENGE/);assert.doesNotThrow(()=>assertAdmControl({classification:"NO_SIGNIFICANT_AUTOMATED_DECISION",humanChallengeAvailable:false,classificationReference:"ADM-002"}));});
test("S5-G15 non-advised journey preserves customer decision and versioned demands-needs eligibility rules",()=>{const journey={nonAdvised:true,customerSelectsObjective:true,customerMakesFinalDecision:true,suitabilityRecommendation:false,demandsNeedsRulesVersion:"dn-v1",eligibilityRulesVersion:"elig-v1"};assert.doesNotThrow(()=>assertNonAdvisedJourney(journey));assert.throws(()=>assertNonAdvisedJourney({...journey,suitabilityRecommendation:true}),/BOUNDARY_VIOLATION/);assert.throws(()=>assertNonAdvisedJourney({...journey,eligibilityRulesVersion:undefined}),/RULES_REQUIRED/);});
